apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: jenkins
spec:
  selector:
    app: jenkins
  ports:
  - name: http
    port: 8080 # the default Jenkins application port
    targetPort: 8080 
    protocol: TCP
  - name: agent
    port: 50000 # used by inbound agents
    protocol: TCP

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jenkins-home
spec:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 8Gi
  